import levelData from '../level-data';

export default {
  is_2024: false,
  levelData: levelData,
  level: 1,
  characterName: '',
  race: '',
  background: '',
  className: '',
  xp: 0,
  alignment: '',
  hp: 0,
  maxHp: 0,
  tempHp: 0,
  hitDie: '1d8',
  totalHitDie: 1,
  ac: 10,
  speed: 25,
  initiative: 0,
  proficiencyOverride: null,
  inspiration: false,
  shortRests: 0,
  deathSaves: {
    successes: [false, false, false],
    failures: [false, false, false],
  },
  conditions: '',
  concentration: '',
  abilities: [
    { name: 'STR', score: 10 },
    { name: 'DEX', score: 10 },
    { name: 'CON', score: 10 },
    { name: 'INT', score: 10 },
    { name: 'WIS', score: 10 },
    { name: 'CHA', score: 10 },
  ],
  savingThrows: [
    { name: 'STR', proficient: false },
    { name: 'DEX', proficient: false },
    { name: 'CON', proficient: false },
    { name: 'INT', proficient: false },
    { name: 'WIS', proficient: false },
    { name: 'CHA', proficient: false },
  ],
  skills: [
    { name: 'Acrobatics', ability: 'DEX', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Animal Handling', ability: 'WIS', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Arcana', ability: 'INT', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Athletics', ability: 'STR', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Deception', ability: 'CHA', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'History', ability: 'INT', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Insight', ability: 'WIS', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Intimidation', ability: 'CHA', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Investigation', ability: 'INT', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Medicine', ability: 'WIS', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Nature', ability: 'INT', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Perception', ability: 'WIS', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Performance', ability: 'CHA', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Persuasion', ability: 'CHA', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Religion', ability: 'INT', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Sleight of Hand', ability: 'DEX', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Stealth', ability: 'DEX', proficient: false, doubleProficient: false, modifierOverride: null },
    { name: 'Survival', ability: 'WIS', proficient: false, doubleProficient: false, modifierOverride: null },
  ],
  attacks: [],
  coins: [
    { name: 'cp', amount: 0 },
    { name: 'sp', amount: 0 },
    { name: 'ep', amount: 0 },
    { name: 'gp', amount: 0 },
    { name: 'pp', amount: 0 },
  ],
  equipmentText: {},
  proficienciesText: {},
  featuresText: {},
  personalityText: {},
  backstoryText: {},
  treasureText: {},
  organizationsText: {},
  notesText: {},
  spClass: '',
  spAbility: 'WIS',
  spSave: '',
  spAttack: '',
  cantripsList: [],
  lvl1Spells: { slots: 0, expended: 0, spells: [] },
  lvl2Spells: { slots: 0, expended: 0, spells: [] },
  lvl3Spells: { slots: 0, expended: 0, spells: [] },
  lvl4Spells: { slots: 0, expended: 0, spells: [] },
  lvl5Spells: { slots: 0, expended: 0, spells: [] },
  lvl6Spells: { slots: 0, expended: 0, spells: [] },
  lvl7Spells: { slots: 0, expended: 0, spells: [] },
  lvl8Spells: { slots: 0, expended: 0, spells: [] },
  lvl9Spells: { slots: 0, expended: 0, spells: [] },
};
